"use client";

import {
  Activity,
  Ambulance,
  Anchor,
  Apple,
  ArrowLeftRight,
  Atom,
  Baby,
  BadgeDollarSign,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Bot,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cat,
  ChartBar,
  ChartPie,
  Cigarette,
  CircleAlert,
  CircleDollarSign,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Coins,
  Compass,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  Database,
  Dice5,
  Dog,
  Droplets,
  Dumbbell,
  Ellipsis,
  Factory,
  FileText,
  Film,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HandCoins,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Hotel,
  IceCreamCone,
  Image,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Library,
  LineChart,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Mic,
  Microscope,
  Monitor,
  Mountain,
  Music,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  Palmtree,
  PartyPopper,
  PawPrint,
  PenLine,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  PlusCircle,
  Popcorn,
  Printer,
  Receipt,
  Recycle,
  Repeat,
  Rocket,
  Sailboat,
  Salad,
  Scale,
  School,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tablet,
  Tags,
  Target,
  Terminal,
  Thermometer,
  Ticket,
  Timer,
  Train,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  University,
  User,
  Users,
  Utensils,
  Wallet,
  Warehouse,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Keep in sync with backend `category-icons.ts`. */
export const CATEGORY_ICON_IDS = [
  "banknote",
  "circle-dollar-sign",
  "coins",
  "hand-coins",
  "badge-dollar-sign",
  "credit-card",
  "wallet",
  "piggy-bank",
  "landmark",
  "scale",
  "chart-pie",
  "chart-bar",
  "line-chart",
  "trending-up",
  "trending-down",
  "activity",
  "briefcase",
  "building",
  "building-2",
  "factory",
  "warehouse",
  "handshake",
  "users",
  "user",
  "plus-circle",
  "home",
  "bed",
  "bath",
  "sofa",
  "lamp",
  "key",
  "key-round",
  "wrench",
  "hammer",
  "paintbrush",
  "brush",
  "plug",
  "zap",
  "droplets",
  "flame",
  "wifi",
  "smartphone",
  "monitor",
  "laptop",
  "tablet",
  "tv",
  "printer",
  "hard-drive",
  "cloud",
  "database",
  "shopping-cart",
  "shopping-bag",
  "store",
  "utensils",
  "coffee",
  "pizza",
  "cake",
  "cookie",
  "croissant",
  "fish",
  "ice-cream-cone",
  "salad",
  "soup",
  "wine",
  "beer",
  "apple",
  "car",
  "car-front",
  "bus",
  "train",
  "bike",
  "fuel",
  "plane",
  "ship",
  "sailboat",
  "anchor",
  "rocket",
  "map-pin",
  "map",
  "compass",
  "globe",
  "hotel",
  "palmtree",
  "mountain",
  "umbrella",
  "sun",
  "ticket",
  "heart",
  "heart-pulse",
  "stethoscope",
  "hospital",
  "pill",
  "syringe",
  "thermometer",
  "ambulance",
  "dumbbell",
  "bone",
  "smile",
  "glasses",
  "watch",
  "sparkles",
  "scissors",
  "graduation-cap",
  "school",
  "university",
  "library",
  "book",
  "book-open",
  "newspaper",
  "pen-line",
  "pencil",
  "calculator",
  "microscope",
  "flask-conical",
  "atom",
  "cpu",
  "bot",
  "code",
  "terminal",
  "gift",
  "party-popper",
  "crown",
  "gem",
  "star",
  "trophy",
  "medal",
  "target",
  "gamepad-2",
  "dice-5",
  "clapperboard",
  "film",
  "popcorn",
  "music",
  "guitar",
  "headphones",
  "mic",
  "speaker",
  "camera",
  "image",
  "palette",
  "repeat",
  "paw-print",
  "cat",
  "dog",
  "bird",
  "leaf",
  "flower-2",
  "sprout",
  "tree-pine",
  "recycle",
  "package",
  "shirt",
  "footprints",
  "receipt",
  "circle-alert",
  "bell",
  "calendar",
  "clock",
  "timer",
  "mail",
  "phone",
  "lock",
  "shield",
  "gavel",
  "file-text",
  "folder",
  "clipboard-list",
  "tags",
  "ellipsis",
  "arrow-left-right",
  "baby",
  "cigarette",
  "trash-2",
] as const;

export type CategoryIconId = (typeof CATEGORY_ICON_IDS)[number];

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconId, LucideIcon> = {
  "banknote": Banknote,
  "circle-dollar-sign": CircleDollarSign,
  "coins": Coins,
  "hand-coins": HandCoins,
  "badge-dollar-sign": BadgeDollarSign,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "piggy-bank": PiggyBank,
  "landmark": Landmark,
  "scale": Scale,
  "chart-pie": ChartPie,
  "chart-bar": ChartBar,
  "line-chart": LineChart,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "activity": Activity,
  "briefcase": Briefcase,
  "building": Building,
  "building-2": Building2,
  "factory": Factory,
  "warehouse": Warehouse,
  "handshake": Handshake,
  "users": Users,
  "user": User,
  "plus-circle": PlusCircle,
  "home": Home,
  "bed": Bed,
  "bath": Bath,
  "sofa": Sofa,
  "lamp": Lamp,
  "key": Key,
  "key-round": KeyRound,
  "wrench": Wrench,
  "hammer": Hammer,
  "paintbrush": Paintbrush,
  "brush": Brush,
  "plug": Plug,
  "zap": Zap,
  "droplets": Droplets,
  "flame": Flame,
  "wifi": Wifi,
  "smartphone": Smartphone,
  "monitor": Monitor,
  "laptop": Laptop,
  "tablet": Tablet,
  "tv": Tv,
  "printer": Printer,
  "hard-drive": HardDrive,
  "cloud": Cloud,
  "database": Database,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "store": Store,
  "utensils": Utensils,
  "coffee": Coffee,
  "pizza": Pizza,
  "cake": Cake,
  "cookie": Cookie,
  "croissant": Croissant,
  "fish": Fish,
  "ice-cream-cone": IceCreamCone,
  "salad": Salad,
  "soup": Soup,
  "wine": Wine,
  "beer": Beer,
  "apple": Apple,
  "car": Car,
  "car-front": CarFront,
  "bus": Bus,
  "train": Train,
  "bike": Bike,
  "fuel": Fuel,
  "plane": Plane,
  "ship": Ship,
  "sailboat": Sailboat,
  "anchor": Anchor,
  "rocket": Rocket,
  "map-pin": MapPin,
  "map": Map,
  "compass": Compass,
  "globe": Globe,
  "hotel": Hotel,
  "palmtree": Palmtree,
  "mountain": Mountain,
  "umbrella": Umbrella,
  "sun": Sun,
  "ticket": Ticket,
  "heart": Heart,
  "heart-pulse": HeartPulse,
  "stethoscope": Stethoscope,
  "hospital": Hospital,
  "pill": Pill,
  "syringe": Syringe,
  "thermometer": Thermometer,
  "ambulance": Ambulance,
  "dumbbell": Dumbbell,
  "bone": Bone,
  "smile": Smile,
  "glasses": Glasses,
  "watch": Watch,
  "sparkles": Sparkles,
  "scissors": Scissors,
  "graduation-cap": GraduationCap,
  "school": School,
  "university": University,
  "library": Library,
  "book": Book,
  "book-open": BookOpen,
  "newspaper": Newspaper,
  "pen-line": PenLine,
  "pencil": Pencil,
  "calculator": Calculator,
  "microscope": Microscope,
  "flask-conical": FlaskConical,
  "atom": Atom,
  "cpu": Cpu,
  "bot": Bot,
  "code": Code,
  "terminal": Terminal,
  "gift": Gift,
  "party-popper": PartyPopper,
  "crown": Crown,
  "gem": Gem,
  "star": Star,
  "trophy": Trophy,
  "medal": Medal,
  "target": Target,
  "gamepad-2": Gamepad2,
  "dice-5": Dice5,
  "clapperboard": Clapperboard,
  "film": Film,
  "popcorn": Popcorn,
  "music": Music,
  "guitar": Guitar,
  "headphones": Headphones,
  "mic": Mic,
  "speaker": Speaker,
  "camera": Camera,
  "image": Image,
  "palette": Palette,
  "repeat": Repeat,
  "paw-print": PawPrint,
  "cat": Cat,
  "dog": Dog,
  "bird": Bird,
  "leaf": Leaf,
  "flower-2": Flower2,
  "sprout": Sprout,
  "tree-pine": TreePine,
  "recycle": Recycle,
  "package": Package,
  "shirt": Shirt,
  "footprints": Footprints,
  "receipt": Receipt,
  "circle-alert": CircleAlert,
  "bell": Bell,
  "calendar": Calendar,
  "clock": Clock,
  "timer": Timer,
  "mail": Mail,
  "phone": Phone,
  "lock": Lock,
  "shield": Shield,
  "gavel": Gavel,
  "file-text": FileText,
  "folder": Folder,
  "clipboard-list": ClipboardList,
  "tags": Tags,
  "ellipsis": Ellipsis,
  "arrow-left-right": ArrowLeftRight,
  "baby": Baby,
  "cigarette": Cigarette,
  "trash-2": Trash2,
};

export const CATEGORY_ICON_LABELS: Record<CategoryIconId, string> = {
  "banknote": "Banknote",
  "circle-dollar-sign": "Circle Dollar Sign",
  "coins": "Coins",
  "hand-coins": "Hand Coins",
  "badge-dollar-sign": "Badge Dollar Sign",
  "credit-card": "Credit Card",
  "wallet": "Wallet",
  "piggy-bank": "Piggy Bank",
  "landmark": "Landmark",
  "scale": "Scale",
  "chart-pie": "Chart Pie",
  "chart-bar": "Chart Bar",
  "line-chart": "Line Chart",
  "trending-up": "Trending Up",
  "trending-down": "Trending Down",
  "activity": "Activity",
  "briefcase": "Briefcase",
  "building": "Building",
  "building-2": "Building 2",
  "factory": "Factory",
  "warehouse": "Warehouse",
  "handshake": "Handshake",
  "users": "Users",
  "user": "User",
  "plus-circle": "Plus Circle",
  "home": "Home",
  "bed": "Bed",
  "bath": "Bath",
  "sofa": "Sofa",
  "lamp": "Lamp",
  "key": "Key",
  "key-round": "Key Round",
  "wrench": "Wrench",
  "hammer": "Hammer",
  "paintbrush": "Paintbrush",
  "brush": "Brush",
  "plug": "Plug",
  "zap": "Zap",
  "droplets": "Droplets",
  "flame": "Flame",
  "wifi": "Wifi",
  "smartphone": "Smartphone",
  "monitor": "Monitor",
  "laptop": "Laptop",
  "tablet": "Tablet",
  "tv": "Tv",
  "printer": "Printer",
  "hard-drive": "Hard Drive",
  "cloud": "Cloud",
  "database": "Database",
  "shopping-cart": "Shopping Cart",
  "shopping-bag": "Shopping Bag",
  "store": "Store",
  "utensils": "Utensils",
  "coffee": "Coffee",
  "pizza": "Pizza",
  "cake": "Cake",
  "cookie": "Cookie",
  "croissant": "Croissant",
  "fish": "Fish",
  "ice-cream-cone": "Ice Cream Cone",
  "salad": "Salad",
  "soup": "Soup",
  "wine": "Wine",
  "beer": "Beer",
  "apple": "Apple",
  "car": "Car",
  "car-front": "Car Front",
  "bus": "Bus",
  "train": "Train",
  "bike": "Bike",
  "fuel": "Fuel",
  "plane": "Plane",
  "ship": "Ship",
  "sailboat": "Sailboat",
  "anchor": "Anchor",
  "rocket": "Rocket",
  "map-pin": "Map Pin",
  "map": "Map",
  "compass": "Compass",
  "globe": "Globe",
  "hotel": "Hotel",
  "palmtree": "Palmtree",
  "mountain": "Mountain",
  "umbrella": "Umbrella",
  "sun": "Sun",
  "ticket": "Ticket",
  "heart": "Heart",
  "heart-pulse": "Heart Pulse",
  "stethoscope": "Stethoscope",
  "hospital": "Hospital",
  "pill": "Pill",
  "syringe": "Syringe",
  "thermometer": "Thermometer",
  "ambulance": "Ambulance",
  "dumbbell": "Dumbbell",
  "bone": "Bone",
  "smile": "Smile",
  "glasses": "Glasses",
  "watch": "Watch",
  "sparkles": "Sparkles",
  "scissors": "Scissors",
  "graduation-cap": "Graduation Cap",
  "school": "School",
  "university": "University",
  "library": "Library",
  "book": "Book",
  "book-open": "Book Open",
  "newspaper": "Newspaper",
  "pen-line": "Pen Line",
  "pencil": "Pencil",
  "calculator": "Calculator",
  "microscope": "Microscope",
  "flask-conical": "Flask Conical",
  "atom": "Atom",
  "cpu": "Cpu",
  "bot": "Bot",
  "code": "Code",
  "terminal": "Terminal",
  "gift": "Gift",
  "party-popper": "Party Popper",
  "crown": "Crown",
  "gem": "Gem",
  "star": "Star",
  "trophy": "Trophy",
  "medal": "Medal",
  "target": "Target",
  "gamepad-2": "Gamepad 2",
  "dice-5": "Dice 5",
  "clapperboard": "Clapperboard",
  "film": "Film",
  "popcorn": "Popcorn",
  "music": "Music",
  "guitar": "Guitar",
  "headphones": "Headphones",
  "mic": "Mic",
  "speaker": "Speaker",
  "camera": "Camera",
  "image": "Image",
  "palette": "Palette",
  "repeat": "Repeat",
  "paw-print": "Paw Print",
  "cat": "Cat",
  "dog": "Dog",
  "bird": "Bird",
  "leaf": "Leaf",
  "flower-2": "Flower 2",
  "sprout": "Sprout",
  "tree-pine": "Tree Pine",
  "recycle": "Recycle",
  "package": "Package",
  "shirt": "Shirt",
  "footprints": "Footprints",
  "receipt": "Receipt",
  "circle-alert": "Circle Alert",
  "bell": "Bell",
  "calendar": "Calendar",
  "clock": "Clock",
  "timer": "Timer",
  "mail": "Mail",
  "phone": "Phone",
  "lock": "Lock",
  "shield": "Shield",
  "gavel": "Gavel",
  "file-text": "File Text",
  "folder": "Folder",
  "clipboard-list": "Clipboard List",
  "tags": "Tags",
  "ellipsis": "Ellipsis",
  "arrow-left-right": "Arrow Left Right",
  "baby": "Baby",
  "cigarette": "Cigarette",
  "trash-2": "Trash 2",
};

export function isCategoryIconId(
  value: string | null | undefined,
): value is CategoryIconId {
  return Boolean(value && value in CATEGORY_ICON_COMPONENTS);
}

export function normalizeCategoryIcon(
  icon: string | null | undefined,
  fallback: CategoryIconId = "tags",
): CategoryIconId {
  const key = String(icon || "")
    .trim()
    .toLowerCase()
    .replace(/_/g, "-");
  if (key === "ice-cream") return "ice-cream-cone";
  if (key === "building2") return "building-2";
  return isCategoryIconId(key) ? key : fallback;
}

export function getCategoryIconComponent(
  icon: string | null | undefined,
): LucideIcon {
  return CATEGORY_ICON_COMPONENTS[normalizeCategoryIcon(icon)];
}

/** Auto-pick icon from category name/description (no AI). */
export function suggestCategoryIconHeuristic(
  name: string,
  description = "",
): CategoryIconId {
  const text = `${name} ${description}`.toLowerCase();

  const rules: Array<[RegExp, CategoryIconId]> = [
    [/salary|payroll|wage|paycheck/, "banknote"],
    [/freelance|contract|gig|consult/, "briefcase"],
    [/business|company|revenue|startup/, "building-2"],
    [/factory|manufactur/, "factory"],
    [/warehouse|storage|inventory/, "warehouse"],
    [/dividend|capital gain|broker|sip|mutual fund|stock|equity/, "line-chart"],
    [/invest|portfolio|crypto|bitcoin/, "trending-up"],
    [/rent|lease|housing|apartment/, "home"],
    [/mortgage|home loan/, "landmark"],
    [/repair|maintenance|upkeep|fix/, "wrench"],
    [/paint|renovat|decor/, "paintbrush"],
    [/furniture|sofa|couch/, "sofa"],
    [/bed|bedroom|sleep/, "bed"],
    [/bath|plumbing/, "bath"],
    [/tax|gst|property tax/, "receipt"],
    [/grocer|supermarket|kirana|market|provisions/, "shopping-cart"],
    [/dining|restaurant|food|takeout|cafe|meal|lunch|dinner/, "utensils"],
    [/coffee|tea|snack|chai/, "coffee"],
    [/pizza/, "pizza"],
    [/cake|bakery|dessert/, "cake"],
    [/beer|alcohol|bar|pub/, "beer"],
    [/wine/, "wine"],
    [/fuel|petrol|diesel|ev charg|gas station/, "fuel"],
    [/transit|metro|bus|train|commute/, "train"],
    [/uber|ola|cab|taxi|ride hail/, "car"],
    [/bike|scooter|two.?wheel/, "bike"],
    [/vehicle|parking|toll|car service|auto/, "car-front"],
    [/flight|airfare|airport/, "plane"],
    [/hotel|staycation|lodging/, "hotel"],
    [/travel|holiday|vacation|trip|tour/, "palmtree"],
    [/electric|power|electricity bill/, "zap"],
    [/water|water bill/, "droplets"],
    [/internet|broadband|wifi|isp|fiber/, "wifi"],
    [/mobile|phone|prepaid|recharge|sim/, "smartphone"],
    [/gas|lpg|cylinder|cooking gas/, "flame"],
    [/health|medical|pharmacy|doctor|clinic|dental/, "heart-pulse"],
    [/hospital|emergency/, "hospital"],
    [/fitness|gym|sport|yoga|workout/, "dumbbell"],
    [/pet|dog|cat|vet/, "paw-print"],
    [/shop|retail|clothes|apparel|fashion|electronics/, "shopping-bag"],
    [/personal care|salon|groom|spa|beauty/, "sparkles"],
    [/entertain|movie|cinema|hobby|leisure|netflix|spotify/, "clapperboard"],
    [/game|gaming|playstation|xbox/, "gamepad-2"],
    [/music|concert/, "music"],
    [/subscription|streaming|membership|saas/, "repeat"],
    [/educat|tuition|course|school|college|university|learning/, "graduation-cap"],
    [/book|library|reading/, "book-open"],
    [/insur|premium|policy/, "shield"],
    [/loan|emi|debt|credit card bill/, "credit-card"],
    [/sav|emergency fund|fd|deposit/, "piggy-bank"],
    [/transfer|p2p|upi send/, "arrow-left-right"],
    [/gift|donat|charit|zakat/, "gift"],
    [/fee|charge|penalty|bank fee|late fee/, "circle-alert"],
    [/wallet|cash|atm/, "wallet"],
    [/child|baby|kids|daycare/, "baby"],
    [/party|celebration|wedding/, "party-popper"],
    [/utility|bill pay/, "receipt"],
    [/software|cloud|hosting|domain/, "cloud"],
    [/office|stationery/, "pen-line"],
    [/misc|other|general|sundry|uncategor/, "ellipsis"],
  ];

  for (const [pattern, icon] of rules) {
    if (pattern.test(text)) return icon;
  }
  return "tags";
}
